### ISSUE TITLE
Increasing Difficulty (0.1.3)

### ISSUE THREAD

**Issue by Sup3rCondor** [recompense-aps/Raindrop#73]
In my recent testing I have found that the game is too easy. The rate at which objects spawn, and the speed they fly should gradually increase over time thus making the game progressively harder.

**Comment by recompense-aps** [comment]
Here is how i implemented it:
`let t = time elapsed since start of game`
`let C = controlling constant`
`speedDelta = C * ln(t)`

which, visually, looks like this:

![Capture](https://user-images.githubusercontent.com/49694818/73586967-443c8980-4472-11ea-80a2-f4c25dbb77fe.PNG)

we can easily tweak it by changing the value of C

**Comment by recompense-aps** [comment]
finished
